### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by HolyGrail999** [brutal-org/brutal#124]
brutal.sh doesnt work and where is the iso?

**Comment by HolyGrail999** [comment]
nothing
it just exits

**Comment by sleepy-monax** [comment]
This script is expected to be run using bash

**Comment by HolyGrail999** [comment]
/usr/bin/sh: /usr/bin/sh: cannot execute binary file

**Comment by HolyGrail999** [comment]
ok one sec

**Comment by HolyGrail999** [comment]
bash brutal.sh options -r
?? becuase it just exits

**Comment by sleepy-monax** [comment]
Are you using WSL 1 ?

**Comment by HolyGrail999** [comment]
2

**Comment by keyboard-slayer** [comment]
You didn't configure your X server probably, you should try to find how to do so :thinking:

**Comment by HolyGrail999** [comment]
i dont have one

**Comment by HolyGrail999** [comment]
and what about gtk

**Comment by keyboard-slayer** [comment]
You need one if you want to run qemu on WSL 

btw the ISO should be generated

**Comment by Abb1x** [comment]
Use WSLg

**Comment by HolyGrail999** [comment]
> You need one if you want to run qemu on WSL
> 
> btw the ISO should be generated

where is the iso located?

**Comment by HolyGrail999** [comment]
how to run then
and how do i get a iso

**Comment by keyboard-slayer** [comment]
`bash ./brutal.sh -r`

**Comment by HolyGrail999** [comment]
i did
thats the isssue

**Comment by HolyGrail999** [comment]
xserver idk
