### ISSUE TITLE
Unable to build on macOS

### ISSUE THREAD

**Issue by 8-bit-owl** [brutal-org/brutal#137]
I am using macOs and I followed the steps below. Please let me know if I am missing anything.

- Cloned the repo
- followed the steps written in ./meta/building.md
- got the following error
```
make: ld.lld: No such file or directory
make: *** [bin/devel/x86_64-kernel-llvm/kernel.elf] Error 1
```
my system - 
Mac M2, OS - MacOS Venture13

**Comment by sleepy-monax** [comment]
You have to install the homebrew package that contains ld.lld and make sure it's in you $PATH

**Comment by hellisabove** [comment]
Seeing as you're on an apple silicon mac, homebrew installs to a different location than /usr/local/opt. Install llvm and replace the "/usr/local/opt" from building.md to just /opt/homebrew

**Comment by 8-bit-owl** [comment]
Thank you @hellisabove  for the help. changing path from "/usr/local/opt" -> "/opt/homebrew/opt" has resolved the issue.
