### ISSUE TITLE
Problem when building brutal

### ISSUE THREAD

**Issue by Rix565** [brutal-org/brutal#35]
It returns me this error:
In file included from sources/kernel/x86_64/boot.c:21:
sources/kernel/x86_64/stivale2.h:4:10: fatal error: 'stivale/stivale2.h' file not found
#include <stivale/stivale2.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [sources/kernel/.build.mk:37: build/x86_64-llvm/cross/kernel/x86_64/boot.c.o] Error 1

**Comment by Wafelack** [comment]
Did you pull the submodules ?

**Comment by Rix565** [comment]
Uh oh
i forgot that :')

**Comment by Wafelack** [comment]
Run `git submodule update --init --recursive` and retry, it should work just fine.

**Comment by Rix565** [comment]
Ok, build works, but lol your kernel is unstable :')
cpu0: panic: vmm.c: 69: 0xffffffff80201000 is already mapped to 0xa30000

**Comment by Supercip971** [comment]
Or when you clone the repositiry you can add the flag `—recursive`.

**Comment by Supercip971** [comment]
> cpu0: panic: vmm.c: 69: 0xffffffff80201000 is already mapped to 0xa30000

Could you share all the logs please ?

**Comment by sleepy-monax** [comment]
> Ok, build works, but lol your kernel is unstable :')
> cpu0: panic: vmm.c: 69: 0xffffffff80201000 is already mapped to 0xa30000

This bug is now fixed with commit 69b1a89d51fba1dc09edf87cca4d23b7a169c47e
