### ISSUE TITLE
bad percentage makefile

### ISSUE THREAD

**Issue by Supercip971** [brutal-org/brutal#51]
```c
> make run-cc -j11 CONFIG_TOOLCHAIN=llvm
expr: division by zero
   0% host   CC sources/bins/cc/cc.c
expr: division by zero
   0% host   LD build/x86_64-llvm/host/cc
```

**Comment by sleepy-monax** [comment]
This is caused by a time-of-check-to-time-of-use bug in how we compute how much work we have to do, fixing would require a lot of complication in the makefile for no benefits
