### ISSUE TITLE
Error on unused variable

### ISSUE THREAD

**Issue by hellisabove** [brutal-org/brutal#59]
sources/libs/brutal/ds/range.c:117:17: error: unused variable 'range' [-Werror,-Wunused-variable]
    vec_foreach(range, self)

**Comment by sleepy-monax** [comment]
This bug seems to happen when using older clang versions, what is the output of `clang --version`?

**Comment by hellisabove** [comment]
Apple clang version 13.0.0 (clang-1300.0.29.3)

**Comment by hellisabove** [comment]
Solved the issue by installing llvm 12 with homebrew and adding '/usr/local/Cellar/llvm@12/12.0.1_1/bin/' to the path.
