### ISSUE TITLE
Feature suggestion: Add source code comments

### ISSUE THREAD

**Issue by gregkrsak** [brutal-org/brutal#82]
Currently, the majority of the .C source code is undocumented.

Consider that it's often easier to expose oneself to the concepts of a new application when the source can be scanned quickly, and the high-level concepts ingested as fast as possible; if going deeper is needed, the actual code is just a few lines away.

**Comment by sleepy-monax** [comment]
Hi Greg,

I don't use inline comments myself because I think they clutter the code. But we should definitely write more doc :)

We started writing a handbook if you want to take a look https://github.com/brutal-org/brutal/tree/main/book

**Comment by gregkrsak** [comment]
Politely pass. Thanks.
