### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by Daniyal-Warraich** [brutal-org/brutal#99]
When I try to build it on macOS, it works fine for the most part. However, it always now ends in this:
```
make: *** No rule to make target `/opt/homebrew/Cellar/llvm/13.0.0_1/lib/clang/13.0.0/share/asan_ignorelist.txt', needed by `bin/arm64-llvm/host/embed/posix/err.c.o'.  Stop.
```
How do I fix this, or get around this?

**Comment by sleepy-monax** [comment]
Try removing the following lines from the makefile:
```
	-fsanitize=address \
	-fsanitize=undefined
```

**Comment by Daniyal-Warraich** [comment]
I did that, but it's still giving me the same error.

**Comment by sleepy-monax** [comment]
Did you try `make nuke` then `make all`?

**Comment by Daniyal-Warraich** [comment]
It works.
